[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/nginx"
include_regex = "\\d+\\.\\d+\\.?(\\d+)?-alpine(?!-perl)"

[NGINX]
container = "nginx"
registry = "docker.io"
